Blogging Web App/app/main/routes.py
from flask import render_template,url_for,flash,redirect,request,abort,Blueprint
from app.models import Post



main=Blueprint('main',__name__)



@main.route('/')
@main.route('/home')
def home():
    page=request.args.get('page',1,type=int)
    posts=Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template("home.html",posts=posts)


@main.route('/about')
def about():
    return render_template("about.html",title="About")

Blogging Web App/app/posts/routes.py
from flask import render_template,url_for,flash,redirect,request,abort,Blueprint
from app.posts.form import PostForm
# Check
from app.models import Post
from app import db
from flask_login import current_user,login_required

posts=Blueprint('posts',__name__)


@posts.route('/post/new',methods=['GET','POST'])
@login_required
def new_post():
    print('new_post')
    form=PostForm()
    if (form.validate_on_submit()):
        # print('clicked')
        post=Post(title=form.title.data,content=form.content.data,author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your Post Has been created!','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='Account',form=form)

@posts.route('/post/<int:post_id>',methods=['GET','POST'])
def post(post_id):
    # print(post_id)
    post=Post.query.get_or_404(post_id)
    print(post,'this is post')
    return render_template('post.html',title=post.title,post=post,legend='New Post')

@posts.route('/update_post/<int:post_id>/update_post',methods=['GET','POST'])
@login_required
def update_post(post_id):
    # print(post_id)
    post=Post.query.get_or_404(post_id)
    print(post,'this is post')
    if (post.author != current_user  ):
        abort(403)
    form=PostForm()
    if (form.validate_on_submit()):
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()
        flash("your post has been updated!",'success')
        return redirect(url_for('posts.post',post_id=post.id))
    elif (request.method == 'GET'):
        form.title.data=post.title
        form.content.data=post.content
    return render_template('create_post.html',title='Update Post',form=form,legend='Update Post')



@posts.route('/post/<int:post_id>/delete',methods=['GET','POST'])
def delete_post(post_id):
    post=Post.query.get_or_404(post_id)
    print(post,'this is post')
    if (post.author != current_user  ):
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your Post Has Been deleted succesfully','success')

    return redirect(url_for('main.home'))

Blogging Web App/app/users/routes.py
from flask import render_template,url_for,flash,redirect,request,Blueprint

from app.users.form import RegistrationForm,LoginForm,UpdateAccountForm,RequestResetForm,ResetPasswordForm
from app.models import User,Post
from app import db,bcrypt
from flask_login import login_user,current_user,logout_user,login_required


from app.users.form import RegistrationForm,LoginForm,UpdateAccountForm,RequestResetForm,ResetPasswordForm
from app.users.utils import save_picture,send_rest_email



users=Blueprint('users',__name__)



@users.route('/register',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))


    form=RegistrationForm()
    if(form.validate_on_submit()):
        hashed_pw=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(username=form.username.data,email=form.email.data,password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash('Your Account hasbeen created','success')


        # flash(f'Account  created for {form.username.data} !','success')
        return redirect(url_for('user.login'))
        # return redirect(url_for('home'))
    return render_template('register.html',title='Login',form=form)

@users.route('/login',methods=['POST','GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form=LoginForm()
    if(form.validate_on_submit()):
        user=User.query.filter_by(email=form.email.data).first()
        if (user and bcrypt.check_password_hash(user.password,form.password.data)):
            login_user(user,remember=form.remember.data) 
            next_page=request.args.get('next')
            print(next_page)
    
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'login unsuccessfull please check email and password','danger')

    return render_template('login.html',title='Login',form=form)
 
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("main.home"))

@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    # print('in account')
    form=UpdateAccountForm()
    # print(current_user.image_file,'this is the name')
    if(form.validate_on_submit()):
        # print(form.picture.data)
        if(form.picture.data ):
            current_profile_image=current_user.image_file
            picture_file=save_picture(form.picture.data,current_profile_image)
            current_user.image_file=picture_file

        # print('in account')
        current_user.username=form.username.data
        current_user.email=form.email.data
        print(current_user.username,form.username.data)
        db.session.commit()
        flash(f'Your Account has been updated','success')
        return redirect(url_for('account'))
    elif(request.method == 'GET'):
        form.username.data=current_user.username
        form.email.data=current_user.email
    image_file=url_for('static',filename='image/Profile_Default/'+current_user.image_file)
    return render_template("account.html",title='Account',image_file=image_file,form=form)



@users.route('/user/<string:username>')
def user_posts(username):
    page=request.args.get('page',1,type=int)
    user=User.query.filter_by(username=username).first_or_404()

    posts=Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page,per_page=5)
    return render_template("user_post.html",posts=posts,user=user)



@users.route('/reset_password',methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RequestResetForm()

    if (form.validate_on_submit()):
        user=User.query.filter_by(email=form.email.data).first()
        send_rest_email(user)
        flash('An email has been send to rest your password','info')
        return redirect(url_for('users.login'))

    return render_template('reset_request.html',title='Rest Password',form=form)


@users.route('/reset_password/<token>',methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user=User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid expired token','warning')
        return redirect(url_for('users.reset-request'))
    form=ResetPasswordForm()
    if(form.validate_on_submit()):
        hashed_pw=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        
        user.password=hashed_pw
        db.session.commit()
        flash('Your Password has been Updated','success')
        # flash(f'Account  created for {form.username.data} !','success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',title="Rest Password",form=form)

Blogging Web App/app/templates/home.html
{% extends "layout.html" %}
    {% block content %}

        {% for post in posts.items %}

            <article class="media content-section">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='image/Profile_Default/' + post.author.image_file) }}">
                <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts',username=post.author.username) }}" style="text-decoration:none; color: #155a78">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title " style="text-decoration:none; color: #444444"  href="{{ url_for('posts.post',post_id=post.id) }}"> {{ post.title }} </a></h2>
                <p class="article-content"> {{ post.content }} </p>
                </div>
            </article>    


        {% endfor %}


        {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.home',page=page_num) }}"> {{ page_num }} </a>
                {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home',page=page_num) }}"> {{ page_num }} </a>
                
                {% endif %}
                

            {% else %}
                ...
            {% endif %}
        {% endfor %}
{% endblock content %}

Blogging Web App/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link rel="stylesheet" href="{{url_for("static",filename='main.css')}}" >
  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>


    {% if title %}
    <title> Flask Blog {{ title }} </title>

    {% else %}
    
    <title>Flask Blog</title>    

    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{url_for("main.home")}}">Home</a>
                <a class="nav-item nav-link" href="{{url_for("main.about")}}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}

                  <a class="nav-item nav-link" href="{{url_for("posts.new_post")}}">New Post</a>
                  <a class="nav-item nav-link" href="{{url_for("users.account")}}">{{ current_user.username }}</a>
                  <a class="nav-item nav-link" href="{{url_for("users.logout")}}">Logout</a>

                {% else %}
                  <a class="nav-item nav-link" href="{{url_for("users.login")}}">Login</a>
                  <a class="nav-item nav-link" href="{{url_for("users.register")}}">Register</a>
                
                {% endif %}

                
              </div>
            </div>
          </div>
        </nav>
      </header>
      </nav>


      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages=get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category,message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}

                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    
</body>
</html>

Blogging Web App/app/templates/login.html
{% extends "layout.html" %} -->


{% block content %}

    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class='border-bottom mb-4'>Login</legend>
                
                    
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid ") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span> {{ error }} </span>
                                {% endfor %}
                            </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
               
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid ") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span> {{ error }} </span>
                                {% endfor %}
                            </div>
                    {% else %}
                    
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-check">
                    <!-- {{ form.remember(class="form") }} -->
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}

                </div>

                
            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot password</a>
            </small>


        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            
            Need An Account ? <a class="ml-2" href="{{url_for("users.register")}}"> Sign Up</a>
        </small>
    </div>


{% endblock %}

Blogging Web App/app/templates/post.html
{% extends "layout.html" %}

{% block content %}


   

    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='image/Profile_Default/' + post.author.image_file) }}">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts',username=post.author.username) }}" style="text-decoration:none; color: #155a78">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>



            {% if post.author == current_user %}
                <div class="">
                    <a class="btn btn-sm btn-secondary mt-1 mb-2" href="{{ url_for('posts.update_post',post_id=post.id) }}">Update</a>
                    <button type='button' class='btn-sm m-l' data-toggle="modal" data-target="#deleteModal"  >Delete</button>
                </div>
            {% endif %}
        </div>

        <h2 >  {{ post.title }} </a></h2>
        <p class="article-content"> {{ post.content }} </p>

        </div>
    </article> 
    
    <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-footer"> 
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
                </div>
            </div>
            </div>
        </div>

  
{% endblock content %}

Blogging Web App/app/templates/register.html
{% extends "layout.html" %} -->


{% block content %}

    <div class="content-section">
        <form action="/register" method="POST">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class='border-bottom mb-4'>Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid ") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span> {{ error }} </span>
                                
                                {% endfor %}
                            </div>
                    
                    {% else %}
                            {{ form.username(class="form-control form-control-lg ") }}
                    {% endif %}                   

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid ") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span> {{ error }} </span>
                                {% endfor %}
                            </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
               
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid ") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span> {{ error }} </span>
                                {% endfor %}
                            </div>
                    {% else %}
                    
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid ") }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span> {{ error }} </span>
                                {% endfor %}
                            </div>
                    {% else %}
                    
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>


        </form>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            Alraedy Have An Account ? <a class="ml-2" h ref="{{url_for("users.login")}}"> Sign In</a>
        </small>
    </div>


{% endblock %}

Blogging Web App/app/templates/user_post.html
{% extends "layout.html" %}
    {% block content %}

    <h1 classmb-3> Posted By {{ user.username }}  ({{ posts.total }}) </h1>

        {% for post in posts.items %}

            <article class="media content-section">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='image/Profile_Default/' + post.author.image_file) }}">
                <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts',username=post.author.username) }}" style="text-decoration:none; color: #155a78">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title " style="text-decoration:none; color: #444444"  href="{{ url_for('posts.post',post_id=post.id) }}"> {{ post.title }} </a></h2>
                <p class="article-content"> {{ post.content }} </p>
                </div>
            </article>    


        {% endfor %}


        {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href = "{{ url_for('users.user_posts',username=user.username,page=page_num) }}"> {{ page_num }} </a>
                {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts',username=user.username,page=page_num) }}"> {{ page_num }} </a>
                
                {% endif %}
                

            {% else %}
                ...
            {% endif %}
        {% endfor %}
{% endblock content %}